### ISSUE TITLE
Github Actionの自動チェックの権限エラー＆エラー対処（2025/05/20/Tue)

### ISSUE THREAD

**Issue by Rana-s9** [Rana-s9/online_room#51]
Github Actionの自動チェックの権限エラー＆エラー対処（2025/05/20/Tue)しました。

# エラー内容
- bin/railsで権限エラー
- bin/rubocopで権限エラー
- bin/brakemanで権限エラー

権限エラーで、まずチェックができていなかったので
権限エラーを解消しました。以下コマンドを上記３ファイルに対して実行しました。
# 対処法(bin/rubocopの例)
```
docker compose exec web chmod +x bin/rubocop
git update-index --chmod=+x bin/rubocop
git commit -m "Fix:check_permissions"
git push
```

上記でチェックが行われるようになり、testが走った後にエラーが発生しました。
# エラー対処
```
# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html

# This model initially had no columns defined. If you add columns to the
# model remove the "{}" from the fixture names and add the columns immediately
# below each fixture, per the syntax in the comments below
#
one:
  name: TestUserOne
  email: testuserone@example.com
  encrypted_password: <%= Devise::Encryptor.digest(User, 'password123') %>

# column: value
#
two:
  name: TestUserTwo
  email: testusertwo@example.com
  encrypted_password: <%= Devise::Encryptor.digest(User, 'password123') %>
# column: value
```
ユーザーのnameがnullでは登録できない制約があるが
testに書いていないため、エラーが起きていました。
usersモデルに合わせた書き方に編集しました。

# 結果
権限エラー＆エラーともに解消しました。
